// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "ObjBase.h"
#include "WTypes.h"
#include "OLEAuto.h"
#include "indicators.h"

/////////////////////////////////////////////////////////////////////////////
// CIndicators

IMPLEMENT_DYNCREATE(CIndicators, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CIndicators properties

short CIndicators::GetColor()
{
	short result;
	GetProperty(0x1, VT_I2, (void*)&result);
	return result;
}

void CIndicators::SetColor(short propVal)
{
	SetProperty(0x1, VT_I2, propVal);
}

BOOL CIndicators::GetState()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CIndicators::SetState(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

long CIndicators::GetMomentaryTime()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CIndicators::SetMomentaryTime(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

long CIndicators::GetFlashOffTime()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CIndicators::SetFlashOffTime(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

long CIndicators::GetFlashOnTime()
{
	long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CIndicators::SetFlashOnTime(long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

BOOL CIndicators::GetIsFlashing()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CIndicators::SetIsFlashing(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CIndicators operations

void CIndicators::MomentaryOn()
{
	InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CIndicators::MomentaryOff()
{
	InvokeHelper(0x8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CIndicators::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
