#if !defined(AFX_INDICATORS_H__28B06F20_F4B1_11D1_9149_0060089615C2__INCLUDED_)
#define AFX_INDICATORS_H__28B06F20_F4B1_11D1_9149_0060089615C2__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CIndicators wrapper class

class CIndicators : public CWnd
{
protected:
	DECLARE_DYNCREATE(CIndicators)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x97e2126, 0x9f0c, 0x11d1, { 0x90, 0x80, 0x0, 0x60, 0x8, 0x96, 0x15, 0xc2 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	short GetColor();
	void SetColor(short);
	BOOL GetState();
	void SetState(BOOL);
	long GetMomentaryTime();
	void SetMomentaryTime(long);
	long GetFlashOffTime();
	void SetFlashOffTime(long);
	long GetFlashOnTime();
	void SetFlashOnTime(long);
	BOOL GetIsFlashing();
	void SetIsFlashing(BOOL);

// Operations
public:
	void MomentaryOn();
	void MomentaryOff();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_INDICATORS_H__28B06F20_F4B1_11D1_9149_0060089615C2__INCLUDED_)
