//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Eclipse.rc
//
#define ID_COPY                         2
#define IDD_ABOUTBOX                    100
#define IDD_CUSTOM_FILEOPEN             101
#define IDB_SPLASH                      102
#define IDC_ZOOM                        106
#define IDR_MAINFRAME                   128
#define IDR_FASTFTYPE                   129
#define IDD_PROPERTIES                  130
#define IDD_INSTSTATUSBAR               131
#define IDD_ACQTAB                      132
#define IDD_CALTAB                      133
#define IDD_COMP_ADVANCED               135
#define IDD_SELECTED_PROPS              138
#define IDD_GRAPH_PROPS                 139
#define IDD_DIALOG1                     140
#define IDD_INFOBAR                     143
#define IDD_TREND_SAVE                  144
#define IDD_GRAPH_PROPERTIES            145
#define IDD_OVERLAY_PROPS               147
#define IDD_CAL_VIEW                    149
#define IDD_ADD_ITEM                    151
#define IDR_RIGHT_TREND                 155
#define IDR_RIGHT_AVERAGE               156
#define IDD_YAXIS_SCALE                 157
#define IDR_RIGHT_CAL                   158
#define IDD_MODIFY_DATA                 159
#define IDI_ADD                         160
#define IDI_SUBTRACT                    161
#define IDI_DIVIDE                      162
#define IDI_MULTIPLY                    163
#define IDD_SELECTED_TOF_PROPS          164
#define IDD_DIALOG2                     169
#define IDD_TREND_SETUP                 169
#define IDR_TOOLBAR1                    171
#define IDD_RECALC_DLG                  173
#define IDD_SHOWFFT                     183
#define IDD_GENERAL                     403
#define IDD_PROTOCOL1                   404
#define IDD_PROTOCOL2                   405
#define IDD_PROTOCOL3                   406
#define IDD_PROTOCOL4                   407
#define IDD_PROTOCOL5                   408
#define IDD_PROTOCOL6                   409
#define IDD_PROTOCOL7                   410
#define IDD_PROTOCOL8                   411
#define IDD_PROTOCOL_ADVANCED           412
#define IDD_ANATAB                      413
#define IDC_BLOCKS                      1000
#define IDC_ICSVERSION                  1000
#define IDC_GSXVERSION                  1002
#define IDC_SHOWSYMBOL                  1003
#define IDC_BINWIDTH_HALF               1005
#define IDC_BINWIDTH_ONE                1006
#define IDC_BINWIDTH_TWO                1007
#define IDC_ACQUISITION_RATE            1008
#define IDC_TITLE                       1009
#define IDC_CONT_VERT_AUTO              1010
#define IDC_WRITE                       1011
#define IDC_RECORDLENGTH                1013
#define IDC_PROTOCOL                    1015
#define IDC_PROTOCOLSPIN                1016
#define IDC_TIME                        1017
#define IDC_TRIGGERDELAY                1019
#define IDC_PERIOD                      1020
#define IDC_OFFSET                      1021
#define IDC_RECORDPRESET                1022
#define IDC_DEADTIME                    1024
#define IDC_SLS                         1025
#define IDC_GATTI                       1026
#define IDC_POSITIVEPOLARITY            1027
#define IDC_NEGATIVEPOLARITY            1028
#define IDC_RPS                         1029
#define IDC_PRESETTIME                  1030
#define IDC_SPECTRUMPRESET              1031
#define IDC_DIRECT                      1035
#define IDC_SEND                        1036
#define IDC_GSXAVERAGE                  1037
#define IDC_GSXTREND                    1038
#define IDR_AVERAGEVIEW                 1039
#define IDR_TRENDVIEW                   1040
#define IDC_STATUSTAB                   1041
#define ID_INDICATOR_DSP                1042
#define IDC_MODE_AVERAGE                1044
#define IDC_MODE_TREND                  1045
#define IDC_ACQ_START                   1046
#define IDC_ACQ_STOP                    1047
#define IDC_INST_PROPS                  1048
#define IDC_ENHANCER                    1049
#define IDC_COMPRESSION                 1050
#define IDC_NTHRESH_LEVEL               1051
#define IDC_AUTONOISE                   1052
#define IDC_NTHRESHMULT                 1053
#define IDC_ADVANCED                    1054
#define IDC_PERIOD_BACK                 1055
#define IDC_PROTCOL_ADVANCED            1056
#define IDC_WIDTHBACK                   1057
#define IDC_MINTHRESHOLD                1058
#define IDC_WIDTHMAX                    1059
#define IDC_SENSITIVITY                 1060
#define IDC_WIDTHMIN                    1061
#define IDC_PROTECT                     1062
#define IDC_FIRMWARE_VERSION            1063
#define IDC_NO_RELEASE                  1064
#define IDC_ACQ_LED_1                   1065
#define IDC_ACQ_LED_3                   1066
#define IDC_ACQ_LED_2                   1067
#define IDC_MORE                        1068
#define IDC_SEL_PROTOCOL                1069
#define IDC_SEL_MAXACQTIME              1070
#define IDC_SEL_SPECTRAPER              1071
#define IDC_SEL_RPS                     1072
#define IDC_ACQ_MESSAGE                 1073
#define IDC_SEL_TRIGPOL                 1074
#define IDC_SYMBOLS                     1075
#define IDC_SEL_RECLEN                  1076
#define IDC_SEL_RECPERSPEC              1077
#define IDC_SEL_SAMPINTER               1078
#define IDC_SEL_TIMEOFFSET              1079
#define IDC_DIRTREE                     1080
#define IDC_SEL_VERTOFFSET              1081
#define IDC_INFO_DATADIR                1082
#define IDC_SEL_EOSDEAD                 1083
#define IDC_INFO_BROWSE                 1084
#define IDC_SEL_ENHANCER                1085
#define IDC_DIR_FILES                   1086
#define IDC_SEL_COMP                    1087
#define IDC_SEL_SENS                    1088
#define IDC_NAME                        1089
#define IDC_SEL_MINTHRESHOLD            1090
#define IDC_DATA_DIR                    1091
#define IDC_SEL_BKGSAMP                 1092
#define IDC_SPECTRA_ACQ                 1093
#define IDC_SEL_ADJBKG                  1094
#define IDC_ELAPSED_TIME                1095
#define IDC_SEL_MAXPEAKWIDTH            1096
#define IDC_SEL_MINPEAKWIDTH            1097
#define IDC_AVERAGE_NETAREA             1098
#define IDC_SEL_RINGPROTECT             1099
#define IDC_AVERAGE_CENTROID            1101
#define IDC_TITLE_COLOR                 1102
#define IDC_SYMBOLS_COLOR               1103
#define IDC_AVERAGE_GROSSAREA           1104
#define IDC_SEL_CALTYPE                 1105
#define IDC_AVERAGE_END                 1106
#define IDC_SEL_CALNAME                 1107
#define IDC_SYMBOLS_TYPE                1108
#define IDC_AVERAGE_START               1109
#define IDC_LINES                       1110
#define IDC_LINES_COLOR                 1111
#define IDC_MEASURE_RESULT_1            1112
#define IDC_LINES_WIDTH                 1113
#define IDC_GRID                        1114
#define IDC_MEASURE_RESULT_2            1115
#define IDC_GRID_COLOR                  1116
#define IDC_MEASURE_RESULT_3            1117
#define IDC_AXIS_LOG                    1118
#define IDC_MEASURE_RESULT_4            1119
#define IDC_AXIS_COLOR                  1120
#define IDC_AXIS_XTEXT                  1121
#define IDC_AXIS_YTEXT                  1122
#define IDC_SYMBOLS_SIZE                1123
#define IDC_TITLE_TEXT                  1124
#define IDC_BKG_COLOR                   1124
#define IDC_SEL_COMMENT                 1125
#define ID_INSTSTATUS                   1126
#define ID_INFOBAR                      1127
#define TRENDACQUISITION                1128
#define TRENDHOVER                      1129
#define AVERAGEACQUISITION              1130
#define AVERAGEHOVER                    1131
#define DOSTARTACQ						1138 //Added by Paul Walker 160507
#define IDC_OVERLAY_PROPS_BUTTON        1132
#define IDC_OVERLAY_NUMBER              1133
#define IDC_CAL_SAVE                    1134
#define IDC_CAL_UNITS                   1136
#define IDC_ADD_CALVALUE                1137
#define IDC_CAL_FILE                    1141
#define IDC_CALFILE_BROWSE              1142
#define IDC_CAL_CLEAR                   1143
#define IDC_CAL_VIEW                    1144
#define IDC_CAL_LIST                    1147
#define IDC_MARKER_CENTROID             1148
#define IDC_CAL_PATH                    1150
#define IDC_CAL_BROWSE                  1151
#define IDC_CAL_TYPE                    1152
#define IDC_CAL_VALUE                   1153
#define IDC_CAL_TIME                    1154
#define IDC_GSX_CTRL                    1155
#define IDC_CALLIBRARY_LIST             1158
#define IDC_CAL_MESSAGE                 1159
#define IDC_SAVEAS_CALPATH              1160
#define IDC_SAVEAS_BROWSE               1165
#define IDC_APPLY_OPERATOR              1165
#define IDC_VIEW_FFT                    1165
#define IDC_AUTOSCALE                   1165
#define IDC_AVERAGEANA_START            1166
#define IDC_IMPORT                      1166
#define IDC_AVERAGEANA_END              1167
#define IDC_FILE_BROWSE                 1167
#define IDC_AVERAGEANA_CENTROID         1168
#define IDC_FILE_NAME                   1168
#define IDC_APPLY_CONSTANT              1169
#define IDC_SCALE                       1170
#define IDC_FILE_COMBINE                1170
#define IDC_YSCALE_AMPLITUDE            1171
#define IDC_EDIT2                       1171
#define IDC_SPAN_END                    1171
#define IDC_YSCALE_AVE_LSB              1172
#define IDC_CONST_VALUE                 1172
#define IDC_SPAN_END2                   1172
#define IDC_YSCALE_AVE_MVOLT            1173
#define IDC_FILE_OPERATOR               1173
#define IDC_SPAN_END3                   1173
#define IDC_FASTFLIGHT_VER              1174
#define IDC_MEASURE_1                   1174
#define IDC_SPAN_END4                   1174
#define IDC_BUTTON1                     1175
#define IDC_MEASURE_2                   1175
#define IDC_TREND_SETUP                 1175
#define IDC_X_IN                        1175
#define IDC_LIST_MEASURMENTS            1176
#define IDC_X_OUT                       1176
#define IDC_MEASURE_3                   1177
#define IDC_Y_IN                        1177
#define IDC_MEASURE_4                   1178
#define IDC_Y_OUT                       1178
#define IDC_WINDOW                      1179
#define IDC_CENTROID_TEXT               1180
#define IDC_REALCENTROID_TEXT           1181
#define IDC_MOUSE_YAXIS                 1183
#define IDC_MOUSE_XAXIS                 1184
#define IDC_FFTGRAPH                    1185
#define IDC_LOG                         1186
#define IDC_PPM                         1187
#define IDC_PPM_QUAD                    1188
#define IDC_INPUT_FREQ                  1189
#define IDC_TRACK_ENABLE                1190
#define IDC_START_SPAN                  1191
#define IDC_MEASUREMENTS                1192
#define IDC_UPDATE                      1193
#define IDC_TRACK_ENABLE2               1194
#define IDC_START_SPAN2                 1195
#define IDC_REALTIME                    1195
#define IDC_MEASUREMENTS2               1196
#define IDC_DISPLAY                     1196
#define IDC_UPDATE2                     1197
#define IDC_PROGRESS1                   1197
#define IDC_TRACK_ENABLE3               1198
#define IDC_START_SPAN3                 1199
#define IDC_MEASUREMENTS3               1200
#define IDC_UPDATE3                     1201
#define IDC_TRACK_ENABLE4               1202
#define IDC_START_SPAN4                 1203
#define IDC_MEASUREMENTS4               1204
#define IDC_UPDATE4                     1205
#define IDC_SET_REGION                  1206
#define IDC_SET_REGION2                 1207
#define IDC_SET_REGION3                 1208
#define IDC_SET_REGION4                 1209
#define IDC_DEBUGINFO                   1212
#define IDC_MAX_TIME                    1215
#define IDC_MAX_NUMBER                  1216
#define IDM_INSTSTATUSBAR               32771
#define IDM_PROPERTIES                  32772
#define ID_START                        32773
#define ID_STOP                         32775
#define ID_RESET                        32776
#define ID_START_LC                     32777
#define ID_STOP_LC                      32778
#define ID_AUTOSCALE                    32779
#define ID_TREND_FROMFILE               32780
#define ID_AVERAGE_FROMFILE             32781
#define ID_GRAPH_AUTO                   32782
#define ID_GRAPH_VERTAUTO               32783
#define ID_GRAPH_VERTOUT                32784
#define ID_GRAPH_VERTIN                 32785
#define ID_GRAPH_HORZOUT                32786
#define ID_GRAPH_HORZIN                 32787
#define ID_NOT_AVAIL                    32788
#define IDM_FILE_OPEN                   32789
#define ID_BUTTON32790                  32790
#define IDM_FILE_NEW                    32792
#define IDM_COPYGRAPH                   32793
#define IDM_FILE_SAVE                   32794
#define ID_AVERAGE_MODE_START           32795
#define ID_AVERAGE_MODE_STOP            32796
#define ID_TREND_MODE_START             32797
#define ID_TREND_MODE_STOP              32798
#define ID_MENUITEM32799                32799
#define IDM_TREND_MODE                  32800
#define IDM_AVERAGE_MODE                32801
#define ID_GRAPH_ZOOM                   32802
#define ID_VIEWMODE_ZOOM                32803
#define ID_VIEWMODE_MARKER              32804
#define ID_SMOOTH_NONE                  32805
#define ID_SMOOTH_3PT                   32806
#define ID_SMOOTH_5PT                   32807
#define IDM_VIEW_INFOBAR                32808
#define ID_COMPARE_AVERAGE              32809
#define ID_ADD_OVERLAY                  32810
#define ID_REMOVE_OVERLAY               32811
#define IDM_DELETE                      32813
#define IDM_UPDATE                      32814
#define IDM_CAL_ENABLED                 32815
#define IDM_FILE_SAVEAS                 32816
#define IDM_VIEW_PROT0                  32817
#define IDM_VIEW_PROT1                  32818
#define IDM_VIEW_PROT2                  32819
#define IDM_VIEW_PROT3                  32820
#define IDM_VIEW_PROT4                  32821
#define IDM_VIEW_PROT5                  32822
#define IDM_VIEW_PROT6                  32823
#define IDM_VIEW_PROT7                  32824
#define ID_RIGHT_SUM                    32825
#define IDM_UPDATEFILE                  32826
#define IDM_MODIFYDATA                  32827
#define ID_RIGHT_GRAPH_PROPS            32828
#define IDM_VIEW_FFT                    32829
#define ID_RIGHT_NOT                    32830
#define ID_BUTTON32831                  32831
#define IDR_RECALC_ALL                  32832
#define IDM_VIEW_TRACK1                 32834
#define IDM_VIEW_TRACK2                 32835
#define IDM_VIEW_TRACK3                 32836
#define IDM_VIEW_TRACK4                 32837
#define IDR_DATA_PROPS                  32838
#define ID                              32839

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32840
#define _APS_NEXT_CONTROL_VALUE         1217
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
